CREATE TABLE receipt.receipt_temp
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data VARCHAR(255),
    CONSTRAINT pk_receipt_temp PRIMARY KEY (id)
);
comment
on table receipt.receipt_temp is 'Временное хранилище чеков';
comment
on column receipt.receipt_temp.id is 'Идентификатор';
comment
on column receipt.receipt_temp.data is 'Данные полученные с запроса';

-- rollback DROP TABLE receipt.receipt_temp;