spring:
  profiles:
    active: dev
  cloud:
    config:
      enabled: true
      profile: dev
  application:
    name: check-collector
  config:
    import: optional:configserver:${SPRING_CONFIG_IMPORT:http://localhost:8071/}
openapi:
  msCheckCollectorREST:
    base-path: api/latest/